

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from  "./provider";
import { startHealthDecreaseJob } from "@/utility/decreaseHealth";
import { useEffect } from "react";
import { start } from "repl";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  startHealthDecreaseJob()

  return (
    
    <html lang="en">
      
      <Provider>
      <body className={inter.className}>{children}</body>
      
      </Provider>
      
    </html>
  );
}
